### ISSUE TITLE
Error: plugin must be a function or promise

### ISSUE THREAD

**Issue by juiceo** [ShogunPanda/fastify-http-errors-enhanced#1]
Title says it all - I'm trying to register the plugin in the following way, as per the docs:

```
server.register(require('fastify-errors-properties'))

-> Error: plugin must be a function or a promise
```

This happens with Fastify `2.11.0`

**Comment by ShogunPanda** [comment]
Hi, thanks for noticing this. It was a TypeScript configuration problem, which is fixed in `0.6.0`
