### ISSUE TITLE
CommonJS support and ESM build fix

### ISSUE THREAD

**Issue by davityavryan** [ShogunPanda/fastify-http-errors-enhanced#5]
Hey @ShogunPanda ,

First of all, nice package.

I did notice that `esm-pkg-add-imports-extensions` used on line https://github.com/ShogunPanda/fastify-http-errors-enhanced/blob/6683616bd320ca58a5f023e9fa3af365f8175660/package.json#L33 does nothing and your build is ending up having `.js` files which I guess should have been renamed to `.mjs` ones.

Also is there a plan to support CommonJS format too? it is kind of required to have nowadays.

I got a problem using your package(same for `http-errors-enhanced`) because all packages support at least CommonJS but yours. 

If you are ok with having CommonJS version, I can help with PRs. Should be straight forward.

Thanks in advance for your reply.

**Comment by ShogunPanda** [comment]
Hi David.
First of all, the `esm-pkg-add-imports-extensions` is actually doing stuff.
Basically the issue is that in ESM you can import local files without an extension and you can't import folders (assuming `index.js`).
So the command translates this code:

```
import foo from './bar'
import baz from './folder'
```

to 

```
import foo from './bar.js'
import baz from './folder/index.js'
```

This is without changing source file extension.

About CommonJS, I'm not gonna support it. In order to use this module in a CommonJS context, please use the same workwaround I listed here:

https://github.com/ShogunPanda/fastify-print-routes/issues/1

Thanks for your feedback!

**Comment by davityavryan** [comment]
ok. got it.
maybe then fix the package.json? it shows main pointing to ESM module. and maybe just fixing the file names will just fix this kind of problems.

also my problem is not with wrapping it. I am receiving error on import when I want to use tools like Jest.

this way your code requires additional transpiration on user's side. but problem can be easily fixed by using correct extension.

Modules in Node.js need to have `.mjs` extention unless you enable `"type": "module",` in your package.json which will create more problems to be honest.

**Comment by ShogunPanda** [comment]
I agree that I could remove `main` from `package.json` as it is not used anymore. 

But as this module is ESM only, I don't need to use `mjs` extensions as I specify `"type":"module"` for this exact purpose.
You don't need transpilation, just make sure you use `await import` and don't have top-level `import`s.
If it keeps failing, can you provide me a minimal repo which reproduces the problem?

**Comment by davityavryan** [comment]
> You don't need transpilation, just make sure you use `await import` and don't have top-level `import`s.
> If it keeps failing, can you provide me a minimal repo which reproduces the problem?

I am importing your package in TS and using top level import (as shown in readme). I do handle everything TS related, but as of most of the tools like Jest do ignore transiling `/node_modules/` pattern I do get error because of import statement is used.

I will spend some time on our side to understand if issue can be resolved somehow easier. If not then either we will drop your package or fork.

p.s. I might provide example project to reproduce issue depending on my free time.

Thanks for responses.

**Comment by ShogunPanda** [comment]
Yes, that was exactly my point. Even if you are in TS, use `await import` (and note my comment about it in the issue I linked) and it should work even in TS.

**Comment by davityavryan** [comment]
hmmm. I will try. but I don't see `await import` in your readme. :/

**Comment by davityavryan** [comment]
No sorry I need it synchronously.
We will maintain our own copy.

**Comment by ShogunPanda** [comment]
No worries sir, glad to have helped! ^^

**Comment by ShogunPanda** [comment]
Just FYI, you made me notice one thing: no mention about ESM in the README. It's there now. Thanks again!
