### ISSUE TITLE
Other errors than 404?

### ISSUE THREAD

**Issue by trycoon** [ShogunPanda/fastify-http-errors-enhanced#6]
Only NotFound-errors are documented, but what about 400, 401, 403, 406, 500?
How do I throw those?

Thanks!

**Comment by ShogunPanda** [comment]
You can directly import and throw them.
Like:

```js
import { ForbidenError} from 'http-errors-enhanced'

throw new ForbiddenError('No way')
```

Why do you say only NotFound is documented? Because is the only one showing in the README?

**Comment by trycoon** [comment]
Wow that was FAST! Thanks for first class support!
I missed that this package was wrapping another one, "http-errors-enhanced", so the only error-type I found when browsing this code was the NotFoundError. But then I will look into the different variations of errors in the "http-errors-enhanced"-package.
Thanks once more, and for the examples.
