### ISSUE TITLE
Request for a pre-process hook

### ISSUE THREAD

**Issue by trycoon** [ShogunPanda/fastify-http-errors-enhanced#7]
Since this module sets a error-handler, would it be possible to have a pre-process hook, that could be called in the beginning of the error-handler to pre-process the error? A preprocessor here https://github.com/ShogunPanda/fastify-http-errors-enhanced/blob/main/src/handlers.ts#L40 would be nice.
This is because I'm using "fastify-openapi-glue" together with a "security-handler", it will wrapp http-errors and I need to unwrapp them before this error-handler tries to send them back.

https://github.com/seriousme/fastify-openapi-glue/issues/357

**Comment by ShogunPanda** [comment]
Released in v3.1.0!
Enjoy!
