### ISSUE TITLE
Validation errors are returned with http status code 400 instead of 422

### ISSUE THREAD

**Issue by MikaKarjunen** [ShogunPanda/fastify-http-errors-enhanced#8]
Technically it is not wrong to use status code 400 for validations but more specific code would be 422. At least that should be in the options. Broken syntax should return 400, invalid data 422.

"The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a  415 (Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions."
https://datatracker.ietf.org/doc/html/rfc4918#section-11.2

"Sending invalid fields will result in a 422 Unprocessable Entity response."
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#client-errors

**Comment by ShogunPanda** [comment]
I agree on that. I often use it.
I think I should an option to let the user choose whether it was 400 or 422 for validation error.
Will take care of this next week.

**Comment by MikaKarjunen** [comment]
Absolutely brilliant!

**Comment by ShogunPanda** [comment]
Sorry for the delay. Released in [v4.2.0](https://github.com/ShogunPanda/fastify-http-errors-enhanced/releases/tag/v4.2.0)
